events { }

http {
    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://view:3000;  # Puerto del contenedor de frontend
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend:5000;  # Puerto del contenedor backend
        }
    }
}